name: lumen_reader
description: "Aplicativo de leitura de ebooks com IA Gemini integrada."
publish_to: 'none'
version: 1.2.7+8

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.2
  http: ^1.2.2
  url_launcher: ^6.3.0
  syncfusion_flutter_pdf: ^32.1.21
  syncfusion_flutter_pdfviewer: ^32.1.21
  epubx: ^4.0.0
  google_generative_ai: ^0.4.6
  permission_handler: ^11.3.1
  file_picker: ^8.0.0+1
  flutter_html: ^3.0.0-beta.2
  image: ^4.2.0
  pdfx: ^2.4.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  screen_brightness: ^2.1.7
  device_preview: ^1.2.0
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"

dependency_overrides:
  epubx:
    path: vendor/epubx
  image: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
